### ISSUE TITLE
Permissions issue on Mojave

### ISSUE THREAD

**Issue by andreiborisov** [malob/DarkMode.spoon#2]
I guess this issue should be addressed upstream, but still, maybe you can still with it. Spoon doesn't work (doesn't toggle dark mode), and my guess, this is because Hammerspoon didn't ask for permission to automate System Events.app (or asked, but since this feature released in half-broken state in Mojave, it bugged).
Can you confirm that on your machine this permission is given to Hammerspoon? Or maybe you even know how to fix this?

**Comment by malob** [comment]
I don't know how/when it was enabled, but on my machine in "System Preferences -> Security & Privacy -> Privacy -> Automation", "System Events" is checked off under "Hammerspoon".

**Comment by andreiborisov** [comment]
Thanks, it was fixed upstream in Hammerspoon 0.9.73

**Comment by malob** [comment]
Sweet. I just finished a fairly major refactor of the code for this spoon that fixed a bunch of bugs along the way. If you come across any issues, do let me know.
