### ISSUE TITLE
start() and toggle() functions doesn't work

### ISSUE THREAD

**Issue by andreiborisov** [malob/DarkMode.spoon#3]
When I try to use `start()` function with simple `spoon.DarkMode.start()` it doesn't work producing this output:
`init.lua:311: attempt to index a nil value (local 'self')`

Similar problem occurs with `toggle()`:
`init.lua:299: attempt to index a nil value (local 'self')`

**Comment by malob** [comment]
They are methods as opposed to functions. You need to call them with a semicolon e.g.: `spoon.DarkMode:start()`

**Comment by andreiborisov** [comment]
Ah, my bad, sorry😅
