### ISSUE TITLE
Dark mode toggle doesn’t occur on scheduled time

### ISSUE THREAD

**Issue by andreiborisov** [malob/DarkMode.spoon#6]
Dark mode doesn’t toggle on scheduled time
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by malob** [comment]
Silly mistake ended up being the issue. Fixed in commit 43e919b. Main issue was use of `currentTime` rather than `os.time()` in the predicate function of the timer.

**Comment by malob** [comment]
While adding caching for the location value to deal with situations when `hs.location.get()` can't get a location I realized the logic in `nextToggleTime()` wasn't right. It's fixed now, and there should be no remaining issues with the schedule logic.
